
- name: Read bootstrapped state
  stat:
    path: "{{ consul_bootstrap_state }}"
  register: bootstrap_state
  ignore_errors: true
  tags: always


- name: Include user and group settings
  import_tasks: user_group.yml



- name: Read gossip encryption key for servers that require it
  set_fact:
    consul_raw_key: "{{ lookup('file', '/tmp/consul_raw.key') }}"
  no_log: true
  when:
    - consul_raw_key is not defined

- name: Delete gossip encryption key file
  file:
    path: '/tmp/consul_raw.key'
    state: absent
  become: false
  vars:
    ansible_become: false
  run_once: true
  delegate_to: localhost
  changed_when: false
